### ISSUE TITLE
Fall Back to apple maps issue

### ISSUE THREAD

**Issue by kishorehvk** [googlemaps/OpenInGoogleMaps-iOS#10]
How could i fall back to apple maps when google maps are not installed. I tried but its not working. Could u guide me in that.

**Comment by domesticmouse** [comment]
This library is deprecated. Please use [Maps URLs](https://developers.google.com/maps/documentation/urls/guide) instead. From the overview on the linked page:

Using Maps URLs, you can build a universal, cross-platform URL to launch Google Maps and perform searches, get directions and navigation, and display map views and panoramic images. The URL syntax is the same regardless of the platform in use.
