### ISSUE TITLE
Navigation With Multiple Destinations

### ISSUE THREAD

**Issue by SnehaDudhat** [googlemaps/OpenInGoogleMaps-iOS#11]
there's only starting point & ending point I can set to navigate..
what if I want to add middle points in between starting & ending location?

**Comment by domesticmouse** [comment]
This library is deprecated. Please use [Maps URLs](https://developers.google.com/maps/documentation/urls/guide) instead. From the overview on the linked page:

Using Maps URLs, you can build a universal, cross-platform URL to launch Google Maps and perform searches, get directions and navigation, and display map views and panoramic images. The URL syntax is the same regardless of the platform in use.
