### ISSUE TITLE
Callback to main app not working

### ISSUE THREAD

**Issue by argyrus** [googlemaps/OpenInGoogleMaps-iOS#13]
In navigation mode, when the navigation is successfully completed in Google Maps the callback to the app (that requested the directions) is not called.

**Comment by domesticmouse** [comment]
This library is deprecated. Please use [Maps URLs](https://developers.google.com/maps/documentation/urls/guide) instead. From the overview on the linked page:

Using Maps URLs, you can build a universal, cross-platform URL to launch Google Maps and perform searches, get directions and navigation, and display map views and panoramic images. The URL syntax is the same regardless of the platform in use.
