### ISSUE TITLE
An Unknown error occurred?

### ISSUE THREAD

**Issue by Nandulucky** [googlemaps/OpenInGoogleMaps-iOS#5]
Hi,

I'm working on Google maps direction using this example. it's working in simulator but it's not working in iPhone device. 
Every time i got an issue of an unknown error occurred.
Im using xcode 7.1.1 and iOS version 9.1.
Please find the below attached screenshot of issue.

Thanks,
Nandu K.
![screen shot 2015-11-23 at 11 50 42 am](https://cloud.githubusercontent.com/assets/10863836/11330889/e30e4338-91d8-11e5-8ea1-d9e04f5294da.png)

**Comment by ToddKerpelman** [comment]
Hmm... that's a pretty vague error message. Thanks, Xcode. :)

At what point are you getting this? When you start running the program? After it starts running?

Are you able to build and run other apps on your iPhone without this problem?

**Comment by domesticmouse** [comment]
This library is deprecated. Please use [Maps URLs](https://developers.google.com/maps/documentation/urls/guide) instead. From the overview on the linked page:

Using Maps URLs, you can build a universal, cross-platform URL to launch Google Maps and perform searches, get directions and navigation, and display map views and panoramic images. The URL syntax is the same regardless of the platform in use.
