### ISSUE TITLE
StreeetView isnt working

### ISSUE THREAD

**Issue by psegerst** [googlemaps/OpenInGoogleMaps-iOS#6]
After updating Google Maps I was not able to get StreetView to work, I believe with the previous version it worked fine.  version 4.1473645 is the current release.

**Comment by ToddKerpelman** [comment]
I have the same issue. I noticed that Google recently released a "Google Street View" app -- perhaps we're supposed to be using that instead. Let me chat with the team and get back to you.

**Comment by psegerst** [comment]
TY!

**Comment by arasu01** [comment]
I too face the same issue any update on this @ToddKerpelman  and @psegerst.

**Comment by ToddKerpelman** [comment]
Hey, gang. I've confirmed the issue with the Google Maps on iOS team and it looks like they'll be pushing out a fix fairly soon. No action should be required on your part once the fix goes out. Stay tuned!

**Comment by ToddKerpelman** [comment]
Hey, all. Did the version of Google Maps released on February 8th address this issue for you? I believe that included the fix for the Street View URL scheme.

**Comment by arasu01** [comment]
@ToddKerpelman Yes it is working fine in the version 4.15.1 released on 16 feb 2015.

**Comment by domesticmouse** [comment]
This library is deprecated. Please use [Maps URLs](https://developers.google.com/maps/documentation/urls/guide) instead. From the overview on the linked page:

Using Maps URLs, you can build a universal, cross-platform URL to launch Google Maps and perform searches, get directions and navigation, and display map views and panoramic images. The URL syntax is the same regardless of the platform in use.
