### ISSUE TITLE
Any plans to port to Swift?

### ISSUE THREAD

**Issue by da-na** [googlemaps/OpenInGoogleMaps-iOS#7]
Hi! 
Do you plan to port to Swift?

**Comment by ToddKerpelman** [comment]
Eventually? It's on my to-do list somewhere; honest!

**Comment by hemangshah** [comment]
Hi @ToddKerpelman, any updates for the swift version?

**Comment by domesticmouse** [comment]
Porting this code to Swift is not a priority for a simple reason, we have a better solution - [Maps URLs](https://developers.google.com/maps/documentation/urls/guide). From the overview of the linked page:

Using Maps URLs, you can build a universal, cross-platform URL to launch Google Maps and perform searches, get directions and navigation, and display map views and panoramic images. The URL syntax is the same regardless of the platform in use.
