### ISSUE TITLE
CFBundleDisplayName sometimes doesn't work for "&x-source="

### ISSUE THREAD

**Issue by shubhank008** [googlemaps/OpenInGoogleMaps-iOS#8]
For some reason, *_CFBundleDisplayName *_gets returned as Nil/Null and as such, the callback name is shown as "Null" in google maps as well.  
I am pretty sure this has something to do with info.plist settings but considering I am using default ones (new project), this certainly needs a fallback fix.  

I have added a if/else check to see if **CFBundleDisplayName** is null, if so, use **CFBundleName**

**Comment by domesticmouse** [comment]
This library is deprecated. Please use [Maps URLs](https://developers.google.com/maps/documentation/urls/guide) instead. From the overview on the linked page:

Using Maps URLs, you can build a universal, cross-platform URL to launch Google Maps and perform searches, get directions and navigation, and display map views and panoramic images. The URL syntax is the same regardless of the platform in use.
